# Generated by Django 4.2.4 on 2023-08-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regApp', '0002_remove_registration_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images'),
        ),
    ]
