# Generated by Django 4.2.4 on 2023-08-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='user',
        ),
    ]
