# Generated by Django 4.2.4 on 2023-08-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='file',
            field=models.FileField(null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
